### ISSUE TITLE
attenuation adjustment

### ISSUE THREAD

**Issue by klslz** [tari01/odio-sacd#1]
Hi.

I am wondering how to adjust the attenuation for the data before they hit the FIRs?
I converted a test iso with classical music and ended up with a > -6dBFS wasted (no data above that level)  DR. 

For a starter you could refer me to the variable that's being used. No need to change the code for now.
I could change it myself and give it a try.

Background: The converted wav based on iso I did with your old sacd version sounded worse then the 16/44.1 CD I had a around. I do not know if it comes from the same master though.

Update: I read that you changed some stuff in the (FIR) filter section. Perhaps you handling the whole still differently now.
the sacd tool converted to 96k be default now with odio-sacd its 88.2 if I'm not mistaken. 

Just let me know. If there'd be an option to reduce the attenuation.  

Thx.

**Comment by klslz** [comment]
"sounds warm and rich" is not very scientific either. ;)

Science knows "empirical evidence" btw. It's not unscientific to gather experiences/subjective impressions.
Based on this input a scientist can start his/her research to nail the subject down basically answering the "WHY is that?" question. It's been done that way for centuries.

***

I've seen that the filters are hardcoded. And I also looked into the code earlier. I couldn't figure out how gain/attenuation gets applied (hardcoded) though. I've see that the fGain variable is used for the filters. That's about it. My limited skills and lack of documentation wouldn't allow for more actions on my side. 

If you can tell me where and how you hardcode gain/attenuation I could change (and hardcode)  it myself to run some preliminary tests.

Thx.

**Comment by tari01** [comment]
You misunderstood my remark about the sound quality not being "scientific" enough - I was also referring to my own "warm and rich" assessment :) What I heard with my ears through my equipment was hardly an objective basis, that's why I chose to trust the graphs only.

I'll revisit this issue as soon as I have time to play with the code...

**Comment by tari01** [comment]
OK, here is the part that may be of interest to you:

In **src/converter/filtersetup.c, line 492**:

```
static void filtersetup_SetCoefs(const double *lCoefs, const int nLength, const double fGain, double *lCoefsOut)
{
    double fGainDB = 0; // Gain in decibels
    double fGainVal = pow(10.0, fGainDB / 20.0); // Gain factor (1.0 means no change)
        
    for (int i = 0; i < nLength; i++)
    {
        lCoefsOut[i] = (double)(lCoefs[nLength - 1 - i] * fGain * fGainVal);
    }
}
```

Also, change the top of the file to this:

```
#include <math.h>
#include "filtersetup.h"
#include "memory.h"
```

**Comment by klslz** [comment]
Thx.

Just for me to understand:

I couldn't find any attenuation (or negative gain) before because it  is hardcoded in your hardcoded FIR filter coefficients. 
Now we'd add "gain" to the filter coefficients to change that hardcoded attenuation.

I just tested it. It doesn't look that bad.

Below a dbFS-max (or max-volume) album scan result.
I'd actually need an album-gain factor based on the highest level
found inside the whole album.


The problem:


```
fGainDB=0

    -7.4
    -7.4
    -14.5
    -7.1
    -6.5
    -6.1


fGainDB=3

    -1.4
    -1.4
    -1.1
    -8.6
    -0.5
    -0.1


```
The highest level would be -6.1dBFS on the album with fGainDB=0
I then applied 3dB ( I first tried 6 and that failed).

The amplitude gets 6dB higher when adding 3dB gain !?!? Why is that? Hmmh.

I use below function to figure out the max dbFS level:

```
runtest() {

DAT=$(pwd)/sacd.iso
BASE=$(pwd)

odio-sacd -i "$DAT" -o "$BASE" -s

while IFS= read -r -d '' file; do 

      maxvol=$(ffmpeg -nostdin -i "$file" -af "volumedetect" -vn -sn -dn -f null /dev/null 2>&1 | grep "max_volume" | awk '{print $5}')
      echo -e "\t$maxvol"
      
done < <(find "$BASE" -name "*.wav" -print0 )
}
```

my code

```
static void filtersetup_SetCoefs(const double *lCoefs, const int nLength, const double fGain, double *lCoefsOut)
{

    double fGainDB = 3; // Gain in decibels
    double fGainVal = pow(10.0, fGainDB / 20.0); // Gain factor (1.0 means no change)

    for (int i = 0; i < nLength; i++)
    {
        lCoefsOut[i] = (double)(lCoefs[nLength - 1 - i] * fGain * fGainVal );
    }
}
```

**Comment by tari01** [comment]
Perhaps you could experiment by directly providing a value for **fGainVal** until you get the desired result, then eventually work out the formula for getting that value from a dB value. This would involve tweaking the **pow(10.0, fGainDB / 20.0)** to something that gives you what you need...

Maybe looking up the ffmpeg source function that converts the amplitude value to a dB value would also help.

**Comment by klslz** [comment]
I now run

```
pow(10.0, fGainDB / 2 / 20.0) 

```
It seems to work fine. 

If I am not mistaken the process is actually called (album) peak normalization. For an "offline" DSP engine, such as odio-sacd  such an option would be very useful. Just hardcoding a fixed attenuation factor prior to a filter as done with odio-sacd is not a perfect solution. Such a new feature would have run a album test conversion first, to figure out the album peak level and in a 2nd run adjust the gain factor accordingly to get the peak normalization done.

For me above tweak will do fine though. I just had a single iso to convert.

Thx for your support.
