### ISSUE TITLE
iso2dsf

### ISSUE THREAD

**Issue by klslz** [tari01/odio-sacd#2]
I am wondering how difficult it would be to implement  a .dsf output format option beside .wav.

All the ingredients you'd have on board.

In the end dfs/dop is also widely supported format nowadays.

Thx.

**Comment by tari01** [comment]
@klslz 

The sacd-extract application already does that, so I see no point in reinventing the wheel here. Plus, sacd-extract already has some nice dsf/dff features that are not present in odio-sacd.
