### ISSUE TITLE
Segmentation fault  due to track names

### ISSUE THREAD

**Issue by whiskytango** [tari01/odio-sacd#3]
Hi,
odio-sacd is giving a segmentation fault with iso's that contain tracks whose names have symbols like : or " so no output is generated at all. The older program sacd just reurned an error for these tracks but processed others in the same iso properly.
Thank you for this very useful program!

**Comment by tari01** [comment]
@whiskytango 

I have replied to your earlier message by mail, but apparently it did not reach you. I would like to ask you to upload the offending ISO(s) to some private location and send me the link via E-mail. I need to have the images to be able to debug this.

**Comment by whiskytango** [comment]
Hi Robert, I have shared on google drive using ***@***.*** - please let
me know when you have it and I will delete again, or if there are any
problems. The tracks with "Double Concerto" appear to be the problem.
Thank you
Karl

**Comment by tari01** [comment]
> Hi Robert, I have shared on google drive using ***@***.*** - please let me know when you have it and I will delete again, or if there are any problems. The tracks with "Double Concerto" appear to be the problem. Thank you Karl

You will also need to mail me the link. Thanks.

**Comment by whiskytango** [comment]
Of course, here it is:
https://drive.google.com/file/d/1irnh8OERG5SpQRH-ophUl75VoggxwpLH/view?usp=sharing
thank you

**Comment by tari01** [comment]
@whiskytango 

I've got the file, you can delete it if you wish. Now, I have tested it, but on my end everything works. Do you have the latest versions? (`libodiosacd 21.3.28` and `odio-sacd 21.1.9`)

**Comment by whiskytango** [comment]
Yes, those are the versions I have just installed thank you. I'll try
re-installing.

**Comment by whiskytango** [comment]
Hi Robert,
Further testing suggests that these file names are the problem when using
an external HDD - odio-sacd works fine with that file on the internal SSD
(once I made some room). Easy to work around. Thank you for checking the
file and helping solve this.
Karl

**Comment by tari01** [comment]
> Hi Robert, Further testing suggests that these file names are the problem when using an external HDD - odio-sacd works fine with that file on the internal SSD (once I made some room). Easy to work around. Thank you for checking the file and helping solve this. Karl

Your external drive is probably formatted to FAT, which has serious filename limitations. Nevertheless, I feel I should add some kind of sanity-check for file creation, so we could at least have a clean exit in case of failure.

Closing this as (kind-of) solved.

**Comment by tari01** [comment]
@whiskytango 

I have updated **libodiosacd** - you should now be able to save files to FAT32 formatted drives.

**Comment by whiskytango** [comment]
Hi Robert,
Thank you for doing this - I'm away at the moment but will get the uploaded
version when I'm home.
all the best
Karl
