### ISSUE TITLE
Great app! But error on install

### ISSUE THREAD

**Issue by heinxyze** [tari01/odio-sacd#7]
Hi there,

love the app, used it often without any issues!

But when moving to a new machine with debian 12.5 I follow the installation instructions (without really knowing what I'm doing...), and after 'cmake ..' I get this:

CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  CMakeLists.txt:27 (find_package)

**Comment by tari01** [comment]
@heinxyze: You are missing pkgconfig, probably because it's a fresh OS:

`sudo apt-get install pkg-config`

Please report back here if this solves your issue.

**Comment by heinxyze** [comment]
It worked!

Thanks a lot for that help!
